### ISSUE TITLE
While installing "ruby-jq" getting compilation error, "implicit declaration of function 'lgamma_r' is invalid in C99"

### ISSUE THREAD

**Issue by maheshchaudharCoupa** [winebarrel/ruby-jq#19]
Platform : MacOS Big Sur 11.4

gem install ruby-jq -v '0.2.1'
Building native extensions. This could take a while...
ERROR:  Error installing ruby-jq:
	ERROR: Failed to build gem native extension.

    current directory: /Users/maheshchaudhar/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/ruby-jq-0.2.1/ext
/Users/maheshchaudhar/.rvm/rubies/ruby-2.7.1/bin/ruby -I /Users/maheshchaudhar/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0 -r ./siteconf20210614-41011-1bck1mq.rb extconf.rb
Buildling jq using packaged libraries.
Downloading jq-1.6.tar.gz 
Extracting jq-1.6.tar.gz into tmp/x86_64-apple-darwin20.5.0/ports/jq/1.6... OK
Running 'autoreconf' for jq 1.6... OK
Running 'configure' for jq 1.6... OK
Running 'compile' for jq 1.6... ERROR, review '/Users/maheshchaudhar/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/ruby-jq-0.2.1/ext/tmp/x86_64-apple-darwin20.5.0/ports/jq/1.6/compile.log' to see what happened. Last lines are:
========================================================================
src/libm.h:218:9: warning: 'gamma' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
LIBM_DD(gamma)
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/math.h:755:15: note: 'gamma' has been explicitly marked deprecated here
extern double gamma(double)
              ^
In file included from src/builtin.c:157:
src/libm.h:278:9: warning: 'significand' is deprecated: first deprecated in macOS 10.9 - Use `2*frexp( )` or `scalbn(x, -ilogb(x))` instead. [-Wdeprecated-declarations]
LIBM_DD(significand)
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/math.h:758:15: note: 'significand' has been explicitly marked deprecated here
extern double significand(double)
              ^
src/builtin.c:194:31: error: implicit declaration of function 'lgamma_r' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  jv ret = JV_ARRAY(jv_number(lgamma_r(jv_number_value(input), &sign)));
                              ^
3 warnings and 1 error generated.
make[2]: *** [src/builtin.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/maheshchaudhar/.rvm/rubies/ruby-2.7.1/bin/$(RUBY_BASE_NAME)
	--use-system-libraries
/Users/maheshchaudhar/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:443:in `block in execute': Failed to complete compile task (RuntimeError)
	from /Users/maheshchaudhar/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:409:in `chdir'
	from /Users/maheshchaudhar/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:409:in `execute'
	from /Users/maheshchaudhar/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:137:in `compile'
	from /Users/maheshchaudhar/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:180:in `cook'
	from extconf.rb:27:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/maheshchaudhar/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/ruby-jq-0.2.1 for inspection.
Results logged to /Users/maheshchaudhar/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-20/2.7.0/ruby-jq-0.2.1/gem_make.out
maheshchaudhar@Mahesh-Chaudhars-2021-MacBook-Pro coupa_developme

**Comment by wkrsz** [comment]
I had the same error, and this helped:

```
RUBYJQ_USE_SYSTEM_LIBRARIES=1 gem install ruby-jq
```

Disclaimer: 
![image](https://user-images.githubusercontent.com/54917/126195759-e03a981d-a252-4d20-a320-4dbc226ea0e4.png)

**Comment by utkarshjadhav** [comment]
Thanks but its not working for me! I am still getting the same error -

```
src/builtin.c:194:31: error: implicit declaration of function 'lgamma_r' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  jv ret = JV_ARRAY(jv_number(lgamma_r(jv_number_value(input), &sign)));
```

**Comment by Gerst20051** [comment]
It worked for me by running this: `RUBYJQ_USE_SYSTEM_LIBRARIES=1 bundle install`

**Comment by jakeonfire** [comment]
had to do a little more work to get it to install on my M1 mac --
i re-installed `jq` with homebrew (which installed the arm64 version), added the following to my environment:
```sh
export CPATH="$(brew --prefix)/include:$CPATH"
export LIBRARY_PATH="$(brew --prefix)/lib:$LIBRARY_PATH"
```
and installed the gem with:
```sh
RUBYJQ_USE_SYSTEM_LIBRARIES=1 gem install ruby-jq
```
