### ISSUE TITLE
Error installing ruby-jq on windows using bundler with message Can't create 'jq-jq-1.6/README'

### ISSUE THREAD

**Issue by optimusprime619** [winebarrel/ruby-jq#21]
Environment Info:
Platform: Windows 11 Enterprise Version 22H2
GNU bash, version 5.2.26(1)-release (x86_64-pc-msys)
ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x64-mingw-ucrt]
Bundler version 2.5.6
jq-1.7.1

Error message:

```
$ bundle install
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Installing ruby-jq 0.2.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/ruby-jq-0.2.1/ext
C:/ProgramData/Ruby32-x64/bin/ruby.exe extconf.rb
Buildling jq using packaged libraries.

Downloading jq-1.6.tar.gz
Downloading jq-1.6.tar.gz
...
Downloading jq-1.6.tar.gz
Extracting jq-1.6.tar.gz into tmp/x86_64-w64-mingw32/ports/jq/1.6... ERROR.
Please review logs to see what happened:
----- contents of
'C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/ruby-jq-0.2.1/ext/tmp/x86_64-w64-mingw32/ports/jq/1.6/extract.log'
-----
jq-jq-1.6/README: Can't create 'jq-jq-1.6/README': No such file or directory
bsdtar: Error exit delayed from previous errors.
----- end of file -----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/ProgramData/Ruby32-x64/bin/$(RUBY_BASE_NAME)
        --use-system-libraries
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:623:in
`block in execute': Failed to complete extract task (RuntimeError)
from
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:589:in
`chdir'
from
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:589:in
`execute'
from
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:575:in
`extract_file'
from
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:140:in
`block in extract'
from
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:138:in
`each'
from
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:138:in
`extract'
from
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:233:in
`cook'
        from extconf.rb:27:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/ruby-jq-0.2.1 for inspection.
Results logged to
C:/Users/optimus/.local/share/gem/ruby/3.2.0/extensions/x64-mingw-ucrt/3.2.0/ruby-jq-0.2.1/gem_make.out

  C:/ProgramData/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:119:in `run'
C:/ProgramData/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:28:in
`build'
C:/ProgramData/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:187:in
`build_extension'
C:/ProgramData/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:221:in `block
in build_extensions'
  C:/ProgramData/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `each'
C:/ProgramData/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in
`build_extensions'
C:/ProgramData/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:846:in
`build_extensions'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/rubygems_gem_installer.rb:76:in
`build_extensions'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/source/rubygems.rb:205:in
`install'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/gem_installer.rb:54:in
`install'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/parallel_installer.rb:132:in
`do_install'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/parallel_installer.rb:123:in
`block in worker_pool'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:62:in
`apply_func'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:57:in
`block in process_queue'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:54:in
`loop'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:54:in
`process_queue'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:90:in
`block (2 levels) in create_threads'

An error occurred while installing ruby-jq (0.2.1), and Bundler cannot continue.

In Gemfile:
  ruby-jq
```
Alternatively, tried running 

```
$ RUBYJQ_USE_SYSTEM_LIBRARIES=1 bundle install
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Installing ruby-jq 0.2.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/ruby-jq-0.2.1/ext
C:/ProgramData/Ruby32-x64/bin/ruby.exe extconf.rb
checking for -ljq... no
libjq not found
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/ProgramData/Ruby32-x64/bin/$(RUBY_BASE_NAME)
        --use-system-libraries=true
        --with-jq-dir
        --without-jq-dir
        --with-jq-include
        --without-jq-include=${jq-dir}/include
        --with-jq-lib
        --without-jq-lib=${jq-dir}/lib
        --with-jqlib
        --without-jqlib

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

C:/Users/optimus/.local/share/gem/ruby/3.2.0/extensions/x64-mingw-ucrt/3.2.0/ruby-jq-0.2.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/ruby-jq-0.2.1 for inspection.
Results logged to
C:/Users/optimus/.local/share/gem/ruby/3.2.0/extensions/x64-mingw-ucrt/3.2.0/ruby-jq-0.2.1/gem_make.out

  C:/ProgramData/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:119:in `run'
C:/ProgramData/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:28:in
`build'
C:/ProgramData/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:187:in
`build_extension'
C:/ProgramData/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:221:in `block
in build_extensions'
  C:/ProgramData/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `each'
C:/ProgramData/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in
`build_extensions'
C:/ProgramData/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:846:in
`build_extensions'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/rubygems_gem_installer.rb:76:in
`build_extensions'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/source/rubygems.rb:205:in
`install'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/gem_installer.rb:54:in
`install'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/parallel_installer.rb:132:in
`do_install'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/parallel_installer.rb:123:in
`block in worker_pool'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:62:in
`apply_func'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:57:in
`block in process_queue'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:54:in
`loop'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:54:in
`process_queue'
C:/Users/optimus/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:90:in
`block (2 levels) in create_threads'

An error occurred while installing ruby-jq (0.2.1), and Bundler cannot continue.

In Gemfile:
  ruby-jq
```

Requesting help on identifying and fixing the issue.
Please let me know if any additional information is required.
Thanks!

**Comment by Viktor-Ivliev** [comment]
For ubuntu 24.04 it fixed when install:

`sudo apt insatll jq libjq-dev libonig5`

**Comment by Viktor-Ivliev** [comment]
2025
It seems like they don't want to do anything here... Too bad.
```
 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
38.65 
38.65 current directory:
38.65 /mobile_coach/vendor/bundle/ruby/3.4.0/gems/ruby-jq-0.2.1/ext
38.65 /usr/local/bin/ruby extconf.rb
38.65 checking for -ljq... yes
38.65 creating Makefile
38.65 
38.65 current directory: /mobile_coach/vendor/bundle/ruby/3.4.0/gems/ruby-jq-0.2.1/ext
38.65 make DESTDIR\= sitearchdir\=./.gem.20251205-1-ffevbi
38.65 sitelibdir\=./.gem.20251205-1-ffevbi clean
38.65 
38.65 current directory: /mobile_coach/vendor/bundle/ruby/3.4.0/gems/ruby-jq-0.2.1/ext
38.65 make DESTDIR\= sitearchdir\=./.gem.20251205-1-ffevbi
38.65 sitelibdir\=./.gem.20251205-1-ffevbi
38.65 compiling jq_core.c
38.65 jq_core.c: In function 'rb_jq_alloc':
38.65 jq_core.c:34:3: warning: 'rb_data_object_wrap_warning' is deprecated: by
38.65 TypedData [-Wdeprecated-declarations]
38.65    34 |   return Data_Wrap_Struct(klass, 0, rb_jq_free, p);
38.65       |   ^~~~~~
38.65 In file included from /usr/local/include/ruby-3.4.0/ruby/internal/core.h:27,
38.65                  from /usr/local/include/ruby-3.4.0/ruby/ruby.h:29,
38.65                  from /usr/local/include/ruby-3.4.0/ruby.h:38,
38.65                  from jq_core.h:8,
38.65                  from jq_core.c:1:
38.65 /usr/local/include/ruby-3.4.0/ruby/internal/core/rdata.h:293:1: note: declared
38.65 here
38.65 293 | rb_data_object_wrap_warning(VALUE klass, void *ptr, RUBY_DATA_FUNC mark,
38.65 RUBY_DATA_FUNC free)
38.65       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
38.65 In file included from /usr/local/include/ruby-3.4.0/ruby/internal/assume.h:29,
38.65                  from /usr/local/include/ruby-3.4.0/ruby/backward/2/assume.h:24,
38.65                  from /usr/local/include/ruby-3.4.0/ruby/defines.h:72,
38.65                  from /usr/local/include/ruby-3.4.0/ruby/ruby.h:25:
38.65 jq_core.c: In function 'rb_jq_initialize':
38.65 jq_core.c:42:32: warning: 'rb_data_object_get_warning' is deprecated: by
38.65 TypedData [-Wdeprecated-declarations]
38.65    42 |   Data_Get_Struct(self, struct jq_container, p);
38.65       |                                ^~~~~~~~~~~~
38.65 /usr/local/include/ruby-3.4.0/ruby/internal/cast.h:31:29: note: in definition of
38.65 macro 'RBIMPL_CAST'
38.65    31 | # define RBIMPL_CAST(expr) (expr)
38.65       |                             ^~~~
38.65 jq_core.c:42:3: note: in expansion of macro 'Data_Get_Struct'
38.65    42 |   Data_Get_Struct(self, struct jq_container, p);
38.65       |   ^~~~~~~~~~~~~~~
38.65 /usr/local/include/ruby-3.4.0/ruby/internal/core/rdata.h:325:1: note: declared
38.65 here
38.65   325 | rb_data_object_get_warning(VALUE obj)
```

**Comment by Viktor-Ivliev** [comment]
Hurray! Something new has appeared: https://github.com/persona-id/jq-ruby
